#!/usr/bin/env python3
"""Download the woff2 files the app needs and write static/fonts/fonts.css.

Run once (`python3 scripts/fetch-fonts.py`); the result is committed so the
build never touches the network and the installed PWA renders its own
typography while offline.
"""

import os
import re
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "static", "fonts")
UA = (
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
)
CSS_URL = (
    "https://fonts.googleapis.com/css2"
    "?family=Archivo:wght@400;500;600;700"
    "&family=JetBrains+Mono:wght@400;500;700"
    "&display=swap"
)
WANTED_SUBSETS = {"latin", "latin-ext"}


def get(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read()


def main() -> None:
    os.makedirs(OUT, exist_ok=True)
    css = get(CSS_URL).decode("utf-8")

    blocks = re.findall(r"/\*\s*([\w\-\[\]]+)\s*\*/\s*(@font-face\s*\{.*?\})", css, re.S)
    rules = []
    for subset, block in blocks:
        if subset not in WANTED_SUBSETS:
            continue
        family = re.search(r"font-family:\s*'([^']+)'", block).group(1)
        weight = re.search(r"font-weight:\s*(\d+)", block).group(1)
        style = re.search(r"font-style:\s*(\w+)", block).group(1)
        url = re.search(r"url\((https://[^)]+\.woff2)\)", block).group(1)
        rng = re.search(r"unicode-range:\s*([^;]+);", block).group(1).strip()

        name = f"{family.lower().replace(' ', '-')}-{weight}-{subset}.woff2"
        with open(os.path.join(OUT, name), "wb") as fh:
            fh.write(get(url))
        rules.append(
            "@font-face {\n"
            f"  font-family: '{family}';\n"
            f"  font-style: {style};\n"
            f"  font-weight: {weight};\n"
            "  font-display: swap;\n"
            f"  src: url('/fonts/{name}') format('woff2');\n"
            f"  unicode-range: {rng};\n"
            "}"
        )

    header = "/* Generated by scripts/fetch-fonts.py — self-hosted so the PWA works offline. */\n"
    with open(os.path.join(OUT, "fonts.css"), "w") as fh:
        fh.write(header + "\n".join(rules) + "\n")
    print(f"{len(rules)} @font-face rules -> static/fonts/fonts.css")


if __name__ == "__main__":
    main()
